### PR TITLE
fixed colors

### PR DESCRIPTION
**Pull request by harshsbhandari**
@itsarraj Changed the colors for the home page.

### CODE REVIEW

**Comment by itsarraj** [comment]
@harshsbhandari colors don't look good
image
blue on pink ,
please UI UX made things look good , 
take reference - https://www.youtube.com/watch?v=c9Wg6Cb_YlU

**Comment by harshsbhandari** [comment]
@itsarraj Fixed color of register and signup page

**Comment by itsarraj** [comment]
@harshsbhandari all u did was change color ,

**Comment by harshsbhandari** [comment]
@itsarraj what are your expectations?

**Comment by itsarraj** [comment]
@harshsbhandari first make design on FIGMA.

**Pull request closed without merging**
